name: METAR-archive-cookbook
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - duckdb
  - geopandas
  - metpy
  - lonboard
  - intake
  - intake-parquet
  - intake-xarray
  - s3fs
<<<<<<< HEAD
  - pgeocode
  - pandas
  - numpy
  - hvplot
  - holoviews
  - shapely
  - ipywidgets
  - palettable
  - sidecar
=======
  - pgeocode
>>>>>>> 324a436 (rudy-dev adding boulder station plotting and lonboard visualization)
